name:  Exercise 1 Dummy Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: 😊 Deploy to environment
    runs-on: ubuntu-latest
    environment: development   

    steps:
      - name: Print environment
        run: echo "deploy to ${{ github.environment }}"
