name: Secret Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Print Secret
        run: echo "API Key:${{ secrets.MY_API_KEY }}"
